### ISSUE TITLE
Markdown formatting in cell and multicell fails for some combinations

### ISSUE THREAD

**Issue by Alan-Collins** [py-pdf/fpdf2#1094]
**Environment**
Windows  WSL running Ubuntu 22.04.2
Python 3.11.0
FPDF 2.7.7 from conda (and tested with latest main branch)

**Issue**
When using `cell()` or `multicell()` with `markdown=True`, an error is thrown for some combinations of initial font and markdown modifications. Specifically, the following examples work:

```python
from fpdf import FPDF

pdf = FPDF('P', 'mm', 'Letter')
pdf.add_page()

# works
pdf.set_font('Courier', '', 10)
pdf.cell(40, 10, markdown=True, text="normal")
pdf.ln(10)

# works
pdf.set_font('Courier', '', 10)
pdf.cell(40, 10, markdown=True, text="__italic__")
pdf.ln(10)

# works
pdf.set_font('Courier', '', 10)
pdf.cell(40, 10, markdown=True, text="**bold**")
pdf.ln(10)

# works
pdf.set_font('Courier', 'BI', 10)
pdf.cell(40, 10, markdown=True, text="bold italic")
pdf.ln(10)

pdf.output("test.pdf")
```

While these all fail:

```python
from fpdf import FPDF

pdf = FPDF('P', 'mm', 'Letter')
pdf.add_page()

# fails when combining bold and italic from normal base font
pdf.set_font('Courier', '', 10)
pdf.cell(40, 10, markdown=True, text="__**bold italic**__")
pdf.ln(10)

# fails when adding italic to bold base font
pdf.set_font('Courier', 'B', 10)
pdf.cell(40, 10, markdown=True, text="__bold italic__")
pdf.ln(10)

# fails when negating bold or italic base font
pdf.set_font('Courier', 'B', 10)
pdf.cell(40, 10, markdown=True, text="**normal**")

pdf.output("test.pdf")
```

However, No error occurs if I combine the working and failing snippets into a single script.

To illustrate an error message, If I try just one example of the failing snippets above

```python
from fpdf import FPDF

pdf = FPDF('P', 'mm', 'Letter')
pdf.add_page()

pdf.set_font('Courier', '', 10)
pdf.cell(40, 10, markdown=True, text="__**bold italic**__")
pdf.ln(10)

pdf.output("test.pdf")
```

I get 

```
Traceback (most recent call last):
  File "/mnt/d/work/./test.py", line 30, in <module>
    pdf.cell(40, 10, markdown=True, text="__**bold italic**__")
  File "/home/alan/mambaforge/envs/elgato/lib/python3.11/site-packages/fpdf/fpdf.py", line 217, in wrapper
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/mambaforge/envs/elgato/lib/python3.11/site-packages/fpdf/deprecation.py", line 32, in wrapper
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/mambaforge/envs/elgato/lib/python3.11/site-packages/fpdf/fpdf.py", line 2836, in cell
    styled_txt_frags = self._preload_font_styles(text, markdown)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/mambaforge/envs/elgato/lib/python3.11/site-packages/fpdf/fpdf.py", line 3193, in _preload_font_styles
    frag.font = self.fonts[frag.font_family + frag.font_style]
                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'courierBI'
```

This error does not occur if I first set the font to be Courier with Bold and Italic and then change it back to the normal Courier. i.e.,

```python
from fpdf import FPDF

pdf = FPDF('P', 'mm', 'Letter')
pdf.add_page()

pdf.set_font('Courier', 'BI', 10)
pdf.set_font('Courier', '', 10)
pdf.cell(40, 10, markdown=True, text="__**bold italic**__")
pdf.ln(10)

pdf.output("test.pdf")
```

**Comment by andersonhc** [comment]
In the method [` _preload_font_styles()`](https://github.com/py-pdf/fpdf2/blob/9569ccb5c466193db0949616a873474fcac6e319/fpdf/fpdf.py#L3167) we set the font styles detected in markdown to make sure they exist.
We are doing it for "B", "I", but "BI" is missing.
It should be a simple fix... How do you feel about submitting a PR?
