### ISSUE TITLE
I can't sign

### ISSUE THREAD

**Issue by johnnynunez** [py-pdf/fpdf2#1333]
```
/home/johnny/miniconda3/envs/innovafp/bin/python /home/johnny/Projects/innovafp/src/algorithm/prueba.py 
Traceback (most recent call last):
  File "/home/johnny/Projects/innovafp/src/algorithm/prueba.py", line 1, in <module>
    from fpdf import FPDF
  File "/home/johnny/miniconda3/envs/innovafp/lib/python3.12/site-packages/fpdf/__init__.py", line 24, in <module>
    from .fpdf import (
  File "/home/johnny/miniconda3/envs/innovafp/lib/python3.12/site-packages/fpdf/fpdf.py", line 32, in <module>
    from endesive import signer
  File "/home/johnny/miniconda3/envs/innovafp/lib/python3.12/site-packages/endesive/signer.py", line 14, in <module>
    from oscrypto import asymmetric
  File "/home/johnny/miniconda3/envs/innovafp/lib/python3.12/site-packages/oscrypto/asymmetric.py", line 19, in <module>
    from ._asymmetric import _unwrap_private_key_info
  File "/home/johnny/miniconda3/envs/innovafp/lib/python3.12/site-packages/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/home/johnny/miniconda3/envs/innovafp/lib/python3.12/site-packages/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/home/johnny/miniconda3/envs/innovafp/lib/python3.12/site-packages/oscrypto/util.py", line 14, in <module>
    from ._openssl.util import rand_bytes
  File "/home/johnny/miniconda3/envs/innovafp/lib/python3.12/site-packages/oscrypto/_openssl/util.py", line 6, in <module>
    from ._libcrypto import libcrypto, libcrypto_version_info, handle_openssl_error
  File "/home/johnny/miniconda3/envs/innovafp/lib/python3.12/site-packages/oscrypto/_openssl/_libcrypto.py", line 9, in <module>
    from ._libcrypto_cffi import (
  File "/home/johnny/miniconda3/envs/innovafp/lib/python3.12/site-packages/oscrypto/_openssl/_libcrypto_cffi.py", line 44, in <module>
    raise LibraryNotFoundError('Error detecting the version of libcrypto')
oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto
```

**Comment by Lucas-C** [comment]
Hi @johnnynunez and welcome to the community of `fpdf2` users.

We could be happy to assist you in figuring out a solution to you problem 🙂

However you did not follow the **issue report template**: https://github.com/py-pdf/fpdf2/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

A very important step is mentioned in this template:
> Please include some minimal Python code reproducing your issue.
> If you don't know how to build a minimal reproducible example, please check this tutorial: https://stackoverflow.com/help/minimal-reproducible-example

Without a mention of the version of `fpdf2` that your are using, and some minimal code reprocing your problem, we will not be able to figure what's happening and help you!

**Comment by andersonhc** [comment]
We are getting the same error on our [CI](https://github.com/py-pdf/fpdf2/actions/runs/12484654435)

Looks like an issue between endesive->oscrypto->openssl

**Comment by andersonhc** [comment]
A summary of what I could find:

- since last week "ubuntu-latest" runner is using ubuntu 24 instead of 22
- [Ubuntu 22.04 includes OpenSSL 3.0.2](https://github.com/actions/runner-images/blob/ubuntu24/20241215.1/images/ubuntu/Ubuntu2204-Readme.md)
- [Ubuntu 24.04 includes OpenSSL 3.0.13](https://github.com/actions/runner-images/blob/ubuntu24/20241215.1/images/ubuntu/Ubuntu2404-Readme.md)
- oscrypto 1.3.0 has a regex issue that can't handle OpenSSL version with more than 1 digit on the release version number. [A fix was merged on the repository but a new version was never published on pypi](https://github.com/wbond/oscrypto/issues/78)

**Comment by Lucas-C** [comment]
Thank you very much for the analysis @andersonhc 👍

I fixed the CI pipeline problem by pinning the GitHub Actions runner for now:
https://github.com/py-pdf/fpdf2/pull/1335

**Comment by Lucas-C** [comment]
@johnnynunez: unless you want to provide further information regarding your issue, given that the CI pipeline problem has been solved, we will close this ticket at some point.
