### ISSUE TITLE
Header, footer, page break and image error 

### ISSUE THREAD

**Issue by darkb0ts** [py-pdf/fpdf2#936]
**Error details**
```
Traceback (most recent call last):
  File "d:\Python\exerice.py", line 28, in <module>
    pdf.add_page()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\fpdf\fpdf.py", line 899, in add_page
    self.header()
  File "d:\Python\exerice.py", line 7, in header
    self.image("../docs/fpdf2-logo.png", 10, 8, 33)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\fpdf\fpdf.py", line 217, in wrapper
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\fpdf\fpdf.py", line 3768, in image
    name, img, info = self.preload_image(name, dims)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\fpdf\fpdf.py", line 3864, in preload_image
    info = ImageInfo(get_img_info(name, img, self.image_filter, dims))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\fpdf\image_parsing.py", line 122, in get_img_info
    img_raw_data = load_image(filename)
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\fpdf\image_parsing.py", line 79, in load_image
    with open(filename, "rb") as local_file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../docs/fpdf2-logo.png'
```
**Minimal code**
Please include some minimal Python code reproducing your issue:
```python
from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        # Rendering logo:
        self.image("../docs/fpdf2-logo.png", 10, 8, 33)
        # Setting font: helvetica bold 15
        self.set_font("helvetica", "B", 15)
        # Moving cursor to the right:
        self.cell(80)
        # Printing title:
        self.cell(30, 10, "Title", border=1, align="C")
        # Performing a line break:
        self.ln(20)

    def footer(self):
        # Position cursor at 1.5 cm from bottom:
        self.set_y(-15)
        # Setting font: helvetica italic 8
        self.set_font("helvetica", "I", 8)
        # Printing page number:
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

# Instantiation of inherited class
pdf = PDF()
pdf.add_page()
pdf.set_font("Times", size=12)
for i in range(1, 41):
    pdf.cell(0, 10, f"Printing line number {i}", new_x="LMARGIN", new_y="NEXT")
pdf.output("new-tuto2.pdf")
```

**Environment**
Please provide the following information:
* **Operating System**: Windows
* **Python version**: you can get this information with `Python 3.11.5`
* **`fpdf2` version used**: `fpdf2==2.7.5`

**Comment by pedrogiroldo** [comment]
same issue here

**Comment by Lucas-C** [comment]
> same issue here

And is there an image at this filesystem path, relative to the directory where you execute your script?

**Comment by pedrogiroldo** [comment]
Nevermind, my bad

**Comment by Lucas-C** [comment]
Closing this
