### ISSUE TITLE
AttributeError when table in header and multi-page table in document

### ISSUE THREAD

**Issue by navitho** [py-pdf/fpdf2#943]
Hello!

I get an Attribute Error when I have a table in my header and a multi-page table in my document.  See error details and minimal code below.  The error does not happen if the upper bound on the range call is 10.

thank you for your time!

**Error details**
```
<prompt>$ python3 scripts/table_header_error.py 
Traceback (most recent call last):
  File "scripts/table_header_error.py", line 33, in <module>
    row.cell(datum)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "$HOME/.local/lib/python3.8/site-packages/fpdf/fpdf.py", line 4744, in table
    table.render()
  File "$HOME/.local/lib/python3.8/site-packages/fpdf/table.py", line 144, in render
    row_layout_info = self._get_row_layout_info(i)
  File "$HOME/.local/lib/python3.8/site-packages/fpdf/table.py", line 335, in _get_row_layout_info
    heights_per_cell.append(height)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "$HOME/.local/lib/python3.8/site-packages/fpdf/fpdf.py", line 3313, in _disable_writing
    del self._out
AttributeError: _out
```

**Minimal code**
Please include some minimal Python code reproducing your issue:
```python
from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 8)
        with self.table() as t:
            r = t.row()
            r.cell("headertext")
        self.ln(10)

pdf = PDF()
pdf.add_page()
pdf.set_font("helvetica", "B", 8)

my_list = [
    {
        "AAA": "AAA",
        "BBB": "BBB",
    },
    {
        "CCC": "CCC",
        "DDD": "DDD",
    },
]

with pdf.table() as table:
    for i in range(1, 30):  # range (1,10) works
        for data_row in my_list:
            row = table.row()
            for datum in data_row.values():
                row.cell(datum)

pdf.output("table.pdf")
```

**Environment**
Please provide the following information:
* **Operating System**: Linux Ubuntu 20.04
* **Python version**: Python 3.8.10
* **`fpdf2` version used**: fpdf2==2.7.5

**Comment by Lucas-C** [comment]
Thank you @navitho for reporting this bug

I opened PR #944 to fix this
